/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Component: typeof import('./decorators/component')['Component']
  const Entry: typeof import('./decorators/entry')['Entry']
}
